Better contact_sheet script 📜

diff --git a/bin/contact_sheet b/bin/contact_sheet
--- a/bin/contact_sheet
+++ b/bin/contact_sheet
@@ -1,3 +1,24 @@
-#!/bin/sh
+#!/bin/bash
 
-montage -verbose -label '%f' -font Helvetica -pointsize 20 -background '#000000' -fill 'gray' -define jpeg:size=400x400 -geometry 400x400+4+4 -auto-orient *.jpg contact.jpg
+BOLD_RED='\033[1;31m'
+RESET='\033[0m'
+
+if ! command -v magick &> /dev/null; then
+  echo -e "🪄 ${BOLD_RED}Can't find imagemagick!${RESET}"
+  exit 1
+fi
+
+if [[ -z "$1" ]]; then
+  echo "Usage: contact_sheet <image> (<image 2> ...) <output>"
+  exit 1
+fi
+
+inputs=${*:1:$#-1}
+output=${*:$#}
+rows=$((($#+6)/6))
+
+echo "Generating contact sheet out of $(($#-1)) files..."
+magick montage -label '%f' -font Helvetica -pointsize 30 -background '#000000' -fill '#CCCCCC' \
+  -geometry 400x400+10+10 -auto-orient -tile 6x$rows $inputs "$output"
+
+echo "Generated as $output!"
